algo = input('Digite algo :')
print(f'O tipo primitivo desse valor é : {type(algo)}')

print(f'Só tem espacos? {algo.isspace()}')
print(f'É numerico? {algo.isnumeric()}')
print(f'É alfabetico? {algo.isalpha()}')
print(f'É alfanumerico? {algo.isalnum()}')
print(f'É maiscula? {algo.isupper()}')
print(f'É minuscula? {algo.islower()}')
print(f'É Captalizada {algo.istitle()}')