import random
import time
print('1 - TESOURA\n2 - PEDRA\n3 - PAPEL')
p = int(input('Escolha oque vai jogar: '))
pc = random.randint(1,3)

if p == 1 and pc == 2:
    print('Voce jogou ... ')
    time.sleep(1)
    print('TESOURA')
    time.sleep(1)
    print('A maquina jogou ... ')
    time.sleep(1)
    print('PEDRA')
    time.sleep(1)
    print(f'Voce PERDEU!')
elif p == 1 and pc == 3:
    print('Voce jogou ... ')
    time.sleep(1)
    print('TESOURA')
    time.sleep(1)
    print('A maquina jogou ... ')
    time.sleep(1)
    print('PAPEL')
    time.sleep(1)
    print(f'Voce GANHOU!')
elif p == 2 and pc == 1:
    print('Voce jogou ... ')
    time.sleep(1)
    print('PEDRA')
    time.sleep(1)
    print('A maquina jogou ... ')
    time.sleep(1)
    print('TESOURA')
    time.sleep(1)
    print(f'Voce GANHOU!')
elif p == 2 and pc == 3:
    print('Voce jogou ... ')
    time.sleep(1)
    print('PEDRA')
    time.sleep(1)
    print('A maquina jogou ... ')
    time.sleep(1)
    print('PAPEL')
    time.sleep(1)
    print(f'Voce PERDEU!')
elif p == 3 and pc == 1:
    print('Voce jogou ... ')
    time.sleep(1)
    print('PAPEL')
    time.sleep(1)
    print('A maquina jogou ... ')
    time.sleep(1)
    print('TESOURA')
    time.sleep(1)
    print(f'Voce PERDEU!')
elif p == 3 and pc == 2:
    print('Voce jogou ... ')
    time.sleep(1)
    print('PAPEL')
    time.sleep(1)
    print('A maquina jogou ... ')
    time.sleep(1)
    print('PEDRA')
    time.sleep(1)
    print(f'Voce GANHOU!')
else:
    print('EMPATE')